### ISSUE TITLE
please use tags instead of branches

### ISSUE THREAD

**Issue by asottile** [prettier/pre-commit#21]
pre-commit works best with tags, branches will produce warnings/errors in a future version of pre-commit

thanks!

**Comment by fisker** [comment]
So, let's do it in future.

**Comment by asottile** [comment]
thanks!

**Comment by asottile** [comment]
@fisker this didn't happen for v2.2.0 -- could you please fix this for the future

**Comment by graingert** [comment]
v2.2.0 was not created as a tag, but it appears as though it doesn't work anyway

@fisker not sure why you closed this issue or https://github.com/prettier/pre-commit/issues/27
