### ISSUE TITLE
put `--write` into `entry:` instead of `args`

### ISSUE THREAD

**Issue by asottile** [prettier/pre-commit#22]
this should ease migration from the original prettier/prettier repo:

https://github.com/prettier/pre-commit/blob/42a7d8bd7a9dd6d34a5f2a4e91e0497ad90e65fb/.pre-commit-hooks.yaml#L4-L7

vs

https://github.com/prettier/prettier/blob/7699d2c4936b7b3f3a40c76f0cd66d8bbec8755d/.pre-commit-hooks.yaml#L3

without `--write`, prettier produces not so useful output (lots of file contents)

**Comment by fisker** [comment]
Fixed in https://github.com/prettier/pre-commit/pull/17,

v2.1.2 updated

**Comment by asottile** [comment]
just a note, if someone doesn't want the arguments in `entry` they can override those as well in their own configuration:

```yaml
    -   id: prettier
        entry: prettier  # this removes --write, etc.
        # ...
```
