### ISSUE TITLE
Why branches instead of tags?

### ISSUE THREAD

**Issue by bgusach** [prettier/pre-commit#23]
Hi,

I'm considering using this instead of the prettier repository, but I'm having my doubts about it because there are no tags at all to refer to a stable version. Instead of that there are 103 branches. I don't see the point of using a reference to a branch like `v2.1.2` because any commit may surprisingly change the behaviour or introduce regressions.

Is there a reason behind that?

**Comment by fisker** [comment]
Any problem?

**Comment by bgusach** [comment]
Well, yes... generally speaking versions are pinned in order to avoid unexpected changes. Per definition, a branch is not a specific version. A hash or a well respected tag is.

If I refer to a branch instead of a tag, my code may work today but tomorrow somebody pushes something new, exciting and broken and boom there you go, I have a headache. I don't like headaches 😅.

And not unexpectedly, this doesn't work with `pre-commit autoupdate` as it just fetches the hash of main, because of the aforementioned lack of tags:

```
> pre-commit autoupdate --repo https://github.com/prettier/pre-commit
Updating https://github.com/prettier/pre-commit ... [INFO] Initializing environment for https://github.com/prettier/pre-commit.
updating v2.1.1 -> 36b76b1cf9df45924c11f7a06756a12c9f6cf6c2.
```

**Comment by fisker** [comment]
Point to the hash, if you don't want update.

It's not pinned tag, it's Prettier version, we do updates even Prettier has no new version.

**Comment by graingert** [comment]
@bgusach this is now fixed in https://github.com/pre-commit/mirrors-prettier
